name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
        if: ${{ github.ref == 'refs/heads/main' }}
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '20'
        - name: Install dependencies
          run: npm install
          working-directory: full-stack-open-pokedex
        - run: npm run eslint --fix
          working-directory: full-stack-open-pokedex
        - run: npm run build
          working-directory: full-stack-open-pokedex
        - run: npm test
          working-directory: full-stack-open-pokedex
        - name: e2e tests
          uses: cypress-io/github-action@v5
          with:
            start: npm run start-prod
            working-directory: full-stack-open-pokedex
            command: npm run test:e2e
            wait-on: http://localhost:5000
        - name: Trigger deployment
          run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        - name: Bump version and push tag
          if: ${{ github.ref == 'refs/heads/main' }}
          uses: anothrNick/github-tag-action@1.64.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            WITH_V : true
            PATCH_STRING_TOKEN: true
