name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
 simple_deployment_pipeline:
   runs-on: ubuntu-20.04
   steps:
   - uses: actions/checkout@v4
   - uses: actions/setup-node@v4
     with:
      node-version: '20'
   - name: Install dependencies
     run: npm install
     working-directory: full-stack-open-pokedex
   - run: npm run eslint --fix
     working-directory: full-stack-open-pokedex
   - run: npm run build
     working-directory: full-stack-open-pokedex
   - name: Start application
     working-directory: full-stack-open-pokedex
     run: npm run start-prod

   - name: Run e2e tests
     uses: cypress-io/github-action@v5
     with:
        command: npm run test:e2e
        working-directory: e2e-cypress
